function onOpen() {
  var ui = SpreadsheetApp.getUi();
  ui.createMenu('Setup JSO Tracker')
      .addItem('Initialize New Database', 'setupDatabase')
      .addToUi();
}

const ATTENDANCE_SHEET_ID = '1YQ0uua9CU04SYBSl1MO_kT9UuO8YNYwJyWMm_3tm8GM';
const ATTENDANCE_TAB_NAME = 'Overall Staff';
// Replace this with the ID generated by running setupDatabase()
const JSO_DATA_SHEET_ID = 'YOUR_NEW_JSO_SHEET_ID_HERE';
const MANAGER_EMAIL = 'NapervilleDCManagers@crateandbarrel.com';

function setupDatabase() {
  const ui = SpreadsheetApp.getUi();
  try {
    const newSpreadsheet = SpreadsheetApp.create('JSO Tracking Data');
    const sheet = newSpreadsheet.getActiveSheet();
    sheet.setName('Observations');

    // Headers
    const headers = [['Timestamp', 'Leader', 'Associate', 'Observation Type', 'Notes']];
    sheet.getRange(1, 1, 1, 5).setValues(headers)
         .setFontWeight('bold')
         .setBackground('#d9d9d9');

    sheet.setFrozenRows(1);

    const newId = newSpreadsheet.getId();
    const newUrl = newSpreadsheet.getUrl();

    ui.alert('Success!',
      'A new Google Sheet named "JSO Tracking Data" has been created.\n\n' +
      'ID: ' + newId + '\n\n' +
      'URL: ' + newUrl + '\n\n' +
      'IMPORTANT: Copy the ID above and paste it into line 9 of Code.gs (replacing "YOUR_NEW_JSO_SHEET_ID_HERE"). Then you can deploy the Web App.',
      ui.ButtonSet.OK);

    Logger.log('New JSO Database ID: ' + newId);
    Logger.log('New JSO Database URL: ' + newUrl);
  } catch (e) {
    ui.alert('Error', 'Failed to create database: ' + e.message, ui.ButtonSet.OK);
  }
}

function doGet(e) {
  return HtmlService.createHtmlOutputFromFile('Index')
      .setTitle('JSO Tracker')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1'); // Mobile friendly
}

function getHierarchy() {
  try {
    const attendanceSpreadsheet = SpreadsheetApp.openById(ATTENDANCE_SHEET_ID);
    const sheet = attendanceSpreadsheet.getSheetByName(ATTENDANCE_TAB_NAME);

    if (!sheet) {
      throw new Error("Could not find the tab '" + ATTENDANCE_TAB_NAME + "'.");
    }

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return {};

    // Assuming Column A is Associate, Column B is Leader
    const data = sheet.getRange(2, 1, lastRow - 1, 2).getValues();

    const hierarchy = {};

    for (let i = 0; i < data.length; i++) {
      const associate = String(data[i][0]).trim();
      const leader = String(data[i][1]).trim();

      if (associate && leader) {
        if (!hierarchy[leader]) {
          hierarchy[leader] = [];
        }
        hierarchy[leader].push(associate);
      }
    }

    // Sort associates alphabetically under each leader
    for (const leader in hierarchy) {
        hierarchy[leader].sort();
    }

    return hierarchy;
  } catch (error) {
    Logger.log("Error in getHierarchy: " + error.toString());
    throw new Error("Failed to load staff list. " + error.toString());
  }
}

function submitObservation(data) {
  if (JSO_DATA_SHEET_ID === 'YOUR_NEW_JSO_SHEET_ID_HERE') {
    throw new Error("You must run setupDatabase() and update JSO_DATA_SHEET_ID in Code.gs before submitting data.");
  }

  try {
    const dataSpreadsheet = SpreadsheetApp.openById(JSO_DATA_SHEET_ID);
    const sheet = dataSpreadsheet.getSheetByName('Observations');

    if (!sheet) {
      throw new Error("Could not find the 'Observations' tab in the data sheet.");
    }

    const timestamp = new Date();

    // Append to sheet
    sheet.appendRow([
      timestamp,
      data.leader,
      data.associate,
      data.type,
      data.notes
    ]);

    // Check milestones
    checkMilestones(sheet, data.associate, data.type);

    return { success: true };
  } catch (error) {
    Logger.log("Error in submitObservation: " + error.toString());
    throw new Error("Failed to save observation. " + error.toString());
  }
}

function checkMilestones(sheet, associateName, observationType) {
  try {
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return;

    // Get Associate (Col 3) and Type (Col 4)
    const historyData = sheet.getRange(2, 3, lastRow - 1, 2).getValues();

    let count = 0;
    for (let i = 0; i < historyData.length; i++) {
      if (historyData[i][0] === associateName && historyData[i][1] === observationType) {
        count++;
      }
    }

    // If it's a multiple of 3 (and greater than 0)
    if (count > 0 && count % 3 === 0) {
      sendMilestoneEmail(associateName, observationType, count);
    }

  } catch (error) {
    Logger.log("Error checking milestones: " + error.toString());
    // Don't throw here, we don't want to fail the save just because the email failed.
  }
}

function sendMilestoneEmail(associateName, type, count) {
  let subject = "";
  let body = "";

  if (type === "Positive") {
    subject = "🎉 JSO Milestone: " + associateName + " has reached " + count + " Positive JSOs!";
    body = "Hello Managers,\n\n" +
           "This is an automated notification that " + associateName + " has just received their " + count + "th Positive Job Safety Observation.\n\n" +
           "Please take a moment to congratulate them on their excellent work!\n\n" +
           "Thank you,\nJSO Tracking System";
  } else if (type === "Negative") {
    subject = "⚠️ JSO Alert: " + associateName + " has reached " + count + " Negative JSOs";
    body = "Hello Managers,\n\n" +
           "This is an automated notification that " + associateName + " has just received their " + count + "th Negative Job Safety Observation.\n\n" +
           "This associate may require a CCA or additional coaching.\n\n" +
           "Thank you,\nJSO Tracking System";
  }

  if (subject && body) {
    MailApp.sendEmail({
      to: MANAGER_EMAIL,
      subject: subject,
      body: body
    });
  }
}