const ATTENDANCE_SHEET_ID = '1YQ0uua9CU04SYBSl1MO_kT9UuO8YNYwJyWMm_3tm8GM';
const ATTENDANCE_TAB_NAME = 'Overall Staff';
// Replace this with the ID generated by running setupDatabase()
const JSO_DATA_SHEET_ID = '1FcoCp5ZUsl3zdTdPpxwYiv_jl0LJO6hur6GxaU5lCEo';
const MANAGER_EMAIL = 'NapervilleDCManagers@crateandbarrel.com';
const FUNCTIONS_SHEET_ID = '1WxpuO2fo8PvImyRcEzU_mG-1TF94-_4SQ8Rax8jwIQk';
const FUNCTIONS_TAB_NAME = 'Sheet1';

function setupDatabase() {
  try {
    const newSpreadsheet = SpreadsheetApp.create('JSO Tracking Data');

    // Observations Tab
    const sheet = newSpreadsheet.getActiveSheet();
    sheet.setName('Observations');
    const headers = [['Timestamp', 'Observation ID', 'Topic', 'Leader', 'Associate', 'Observation Type', 'Original Notes', 'Policy Violated', 'Associate Perspective', 'Action Plan', 'Leader Coaching Notes']];
    sheet.getRange(1, 1, 1, 11).setValues(headers)
         .setFontWeight('bold')
         .setBackground('#d9d9d9');
    sheet.setFrozenRows(1);

    // Activity Log Tab
    const logSheet = newSpreadsheet.insertSheet('Activity Log');
    const logHeaders = [['Timestamp', 'Leader', 'Associate', 'Function', 'Observation Type', 'Duration', 'Total Seconds', 'Total Count', 'Calculated UPH', 'Activity Logs', 'Notes 1', 'Notes 2', 'Notes 3', 'Notes 4', 'Notes 5', 'Notes 6', 'Notes 7', 'Notes 8', 'FB: Pace', 'FB: Skills', 'FB: Training', 'FB: Environment', 'FB: Notes', 'Signature']];
    logSheet.getRange(1, 1, 1, logHeaders[0].length).setValues(logHeaders)
         .setFontWeight('bold')
         .setBackground('#d9d9d9');
    logSheet.setFrozenRows(1);

    const newId = newSpreadsheet.getId();
    const newUrl = newSpreadsheet.getUrl();

    Logger.log('=============================================');
    Logger.log('SUCCESS! Database Created.');
    Logger.log('New JSO Database ID: ' + newId);
    Logger.log('New JSO Database URL: ' + newUrl);
    Logger.log('=============================================');
    Logger.log('IMPORTANT: Copy the ID above and paste it into line 4 of Code.gs (replacing "YOUR_NEW_JSO_SHEET_ID_HERE"). Then you can deploy the Web App.');

    console.log('SUCCESS: Database created with ID ' + newId);
  } catch (e) {
    Logger.log('ERROR: Failed to create database. ' + e.message);
    console.error('Failed to create database: ' + e.message);
  }
}

// UPDATED: Now uses createTemplateFromFile and evaluate()
function doGet(e) {
  return HtmlService.createTemplateFromFile('index')
      .evaluate()
      .setTitle('JSO Tracker')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1'); // Mobile friendly
}


// NEW: Helper function to include Styles.html
function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename).getContent();
}

function updateExistingDatabase() {
  try {
    const dataSpreadsheet = SpreadsheetApp.openById(JSO_DATA_SHEET_ID);
    let sheet = dataSpreadsheet.getSheetByName('Observations');
    if (!sheet) {
      throw new Error("Could not find the 'Observations' tab.");
    }

    // Replace the old headers with the new ones, which automatically adds the new columns
    const headers = [['Timestamp', 'Observation ID', 'Topic', 'Leader', 'Associate', 'Observation Type', 'Original Notes', 'Policy Violated', 'Associate Perspective', 'Action Plan', 'Leader Coaching Notes']];
    sheet.getRange(1, 1, 1, 11).setValues(headers)
         .setFontWeight('bold')
         .setBackground('#d9d9d9');


    // Ensure Activity Log exists
    let logSheet = dataSpreadsheet.getSheetByName('Activity Log');
    if (!logSheet) {
      logSheet = dataSpreadsheet.insertSheet('Activity Log');
      const logHeaders = [['Timestamp', 'Leader', 'Associate', 'Function', 'Observation Type', 'Duration', 'Total Seconds', 'Total Count', 'Calculated UPH', 'Activity Logs', 'Notes 1', 'Notes 2', 'Notes 3', 'Notes 4', 'Notes 5', 'Notes 6', 'Notes 7', 'Notes 8', 'FB: Pace', 'FB: Skills', 'FB: Training', 'FB: Environment', 'FB: Notes', 'Signature']];
      logSheet.getRange(1, 1, 1, logHeaders[0].length).setValues(logHeaders)
           .setFontWeight('bold')
           .setBackground('#d9d9d9');
      logSheet.setFrozenRows(1);
    }

    Logger.log('=============================================');
    Logger.log('SUCCESS! Database updated to version 2.');
    Logger.log('The new columns have been added, and Activity Log checked.');
    Logger.log('=============================================');

  } catch (e) {
    Logger.log('ERROR: Failed to update database. ' + e.message);
  }
}


function logActivity(data) {
  try {
    const dataSpreadsheet = SpreadsheetApp.openById(JSO_DATA_SHEET_ID);
    let logSheet = dataSpreadsheet.getSheetByName('Activity Log');

    // Create sheet if it doesn't exist
    if (!logSheet) {
      logSheet = dataSpreadsheet.insertSheet('Activity Log');
    }

    // Update headers if needed (first row check)
    const logHeaders = [
      'Timestamp', 'Leader', 'Associate', 'Function', 'Observation Type',
      'Duration', 'Total Seconds', 'Total Count', 'Calculated UPH',
      'Activity Logs', 'Notes 1', 'Notes 2', 'Notes 3', 'Notes 4', 'Notes 5', 'Notes 6', 'Notes 7', 'Notes 8',
      'FB: Pace', 'FB: Skills', 'FB: Training', 'FB: Environment', 'FB: Notes', 'Signature'
    ];

    const currentHeaders = logSheet.getRange(1, 1, 1, logHeaders.length).getValues()[0];
    if (currentHeaders.length !== logHeaders.length || currentHeaders.join() !== logHeaders.join()) {
      logSheet.getRange(1, 1, 1, logHeaders.length).setValues([logHeaders])
           .setFontWeight('bold')
           .setBackground('#d9d9d9');
      logSheet.setFrozenRows(1);
    }

    // Parse the checklist into 8 columns
    let notesColumns = ["", "", "", "", "", "", "", ""];
    if (data.checklistResults) {
      try {
        let parsed = typeof data.checklistResults === 'string' ? JSON.parse(data.checklistResults) : data.checklistResults;
        let i = 0;
        // Depending on frontend payload, it could be an array of objects
        if (Array.isArray(parsed)) {
            parsed.forEach(item => {
                if (i < 8) {
                    notesColumns[i] = item.check + ": " + (item.notes || "None");
                    i++;
                }
            });
        }
      } catch(e) {
        notesColumns[0] = "Error parsing notes";
      }
    }

    // Process signature
    let signatureUrl = "";
    if (data.signature) {
        try {
            // Remove data URI prefix
            const base64Data = data.signature.split(',')[1];
            const blob = Utilities.newBlob(Utilities.base64Decode(base64Data), 'image/png', 'signature_' + new Date().getTime() + '.png');
            // Save to Drive to get a URL that sheets can use
            const folder = DriveApp.getRootFolder(); // Saving to root folder
            const file = folder.createFile(blob);
            file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
            // Constructing a reliable Google Drive image thumbnail URL for Sheets IMAGE formula
            const imageUrl = "https://drive.google.com/thumbnail?id=" + file.getId() + "&sz=w1000";
            signatureUrl = '=IMAGE("' + imageUrl + '")';
        } catch(e) {
            signatureUrl = "Failed to upload image";
        }
    }

    // Calculate UPH
    let uph = "N/A";
    if (data.totalSeconds > 0 && data.totalCount > 0) {
        uph = Math.round(data.totalCount / (data.totalSeconds / 3600));
    }

    // Format activity logs cleanly
    let activityText = (data.activityLogs || "").replace(/<li>/g, "").replace(/<\/li>/g, "; ").trim();

    const rowData = [
      new Date(),
      data.leader || '',
      data.associate || '',
      data.function || '',
      data.type || '',
      data.duration || '',
      data.totalSeconds || 0,
      data.totalCount || 0,
      uph,
      activityText,
      notesColumns[0],
      notesColumns[1],
      notesColumns[2],
      notesColumns[3],
      notesColumns[4],
      notesColumns[5],
      notesColumns[6],
      notesColumns[7],
      data.fbPace || '',
      data.fbSkills || '',
      data.fbTraining || '',
      data.fbEnvironment || '',
      data.fbNotes || '',
      signatureUrl
    ];

    logSheet.appendRow(rowData);

  } catch(e) {
    Logger.log("Failed to log activity: " + e.toString());
  }
}

function getFunctionsAndUPH() {
  try {
    const cache = CacheService.getScriptCache();
    const cachedData = cache.get('functions_uph');
    if (cachedData) {
      return JSON.parse(cachedData);
    }

    const spreadsheet = SpreadsheetApp.openById(FUNCTIONS_SHEET_ID);
    const sheet = spreadsheet.getSheetByName(FUNCTIONS_TAB_NAME);
    if (!sheet) {
      throw new Error(`Could not find the tab '${FUNCTIONS_TAB_NAME}'.`);
    }

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return [];


    // Assuming Column A is Function, Column B is Expected UPH
    // Read from row 2 down to the last row, 2 columns wide
    const data = sheet.getRange(2, 1, lastRow - 1, 2).getValues();


    const functionsList = [];
    for (let i = 0; i < data.length; i++) {
      const funcName = String(data[i][0]).trim();
      const uph = String(data[i][1]).trim();
      if (funcName) {
        functionsList.push({
          name: funcName,
          uph: uph
        });
      }
    }

    // Store in cache for 4 hours
    cache.put('functions_uph', JSON.stringify(functionsList), 14400);

    return functionsList;
  } catch (error) {
    Logger.log("Error in getFunctionsAndUPH: " + error.toString());
    throw new Error("Failed to load functions and UPH. " + error.toString());
  }
}


function getHierarchy() {
  try {
    const cache = CacheService.getScriptCache();
    const cachedData = cache.get('staff_hierarchy');
    if (cachedData) {
      return JSON.parse(cachedData);
    }

    const attendanceSpreadsheet = SpreadsheetApp.openById(ATTENDANCE_SHEET_ID);
    const sheet = attendanceSpreadsheet.getSheetByName(ATTENDANCE_TAB_NAME);

    if (!sheet) {
      throw new Error("Could not find the tab '" + ATTENDANCE_TAB_NAME + "'.");
    }

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return {};

    // Assuming Column A is Associate, Column B is Leader
    const data = sheet.getRange(2, 1, lastRow - 1, 2).getValues();

    const hierarchy = {};

    for (let i = 0; i < data.length; i++) {
      const associate = String(data[i][0]).trim();
      let leader = String(data[i][1]).trim();

      // Remove any leading numbers and spaces to combine C&B and Temp leaders
      leader = leader.replace(/^\d+\s*/, '').trim();

      if (associate && leader) {
        if (!hierarchy[leader]) {
          hierarchy[leader] = [];
        }
        hierarchy[leader].push(associate);
      }
    }

    // Sort associates alphabetically under each leader
    for (const leader in hierarchy) {
        hierarchy[leader].sort();
    }

    // Store in cache for 4 hours (14400 seconds)
    cache.put('staff_hierarchy', JSON.stringify(hierarchy), 14400);

    return hierarchy;
  } catch (error) {
    Logger.log("Error in getHierarchy: " + error.toString());
    throw new Error("Failed to load staff list. " + error.toString());
  }
}

function submitObservation(data) {
  if (JSO_DATA_SHEET_ID === 'YOUR_NEW_JSO_SHEET_ID_HERE') {
    throw new Error("You must run setupDatabase() and update JSO_DATA_SHEET_ID in Code.gs before submitting data.");
  }

  try {
    const dataSpreadsheet = SpreadsheetApp.openById(JSO_DATA_SHEET_ID);
    const sheet = dataSpreadsheet.getSheetByName('Observations');

    if (!sheet) {
      throw new Error("Could not find the 'Observations' tab in the data sheet.");
    }

    const timestamp = new Date();
    const observationId = Utilities.getUuid();

    // Append to sheet
    // Columns: Timestamp, Obs ID, Topic, Leader, Associate, Type, Notes, Policy, Perspective, Action Plan, Leader Notes
    sheet.appendRow([
      timestamp,
      observationId,
      data.topic,
      data.leader,
      data.associate,
      data.type,
      data.notes,
      '', // Policy
      '', // Perspective
      '', // Action Plan
      ''  // Leader Notes
    ]);

    // Check milestones and email
    handleEmails(sheet, data.associate, data.type, observationId, data.notes, data.topic);

    // Only processJSO logs detailed activities now.


    return { success: true };
  } catch (error) {
    Logger.log("Error in submitObservation: " + error.toString());
    throw new Error("Failed to save observation. " + error.toString());
  }
}

function handleEmails(sheet, associateName, observationType, observationId, note, topic) {
  try {
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return;

    // In v2, Associate is Col 5 and Type is Col 6
    const historyData = sheet.getRange(2, 5, lastRow - 1, 2).getValues();

    let count = 0;
    for (let i = 0; i < historyData.length; i++) {
      if (historyData[i][0] === associateName && historyData[i][1] === observationType) {
        count++;
      }
    }

    const webAppUrl = ScriptApp.getService().getUrl();

    if (observationType === "Negative") {
      // Send an email for EVERY negative JSO
      let subject = "⚠️ Negative JSO Recorded: " + associateName;

      let ccaNote = "";
      if (count > 0 && count % 3 === 0) {
          subject = "🚨 CCA ALERT (Negative JSO #" + count + "): " + associateName;
          ccaNote = "**ATTENTION: This is this associate's " + count + "th Negative JSO. A formal Coaching & Corrective Action (CCA) may be required.**\n\n";
      }

      const calendarLink = "https://calendar.google.com/calendar/render?action=TEMPLATE&text=Coaching%20Conversation:%20" + encodeURIComponent(associateName) + "&details=Discuss%20recent%20Job%20Safety%20Observation.";
      const coachingLink = webAppUrl + "?coaching=true&id=" + observationId + "&associate=" + encodeURIComponent(associateName) + "&note=" + encodeURIComponent(note) + "&topic=" + encodeURIComponent(topic || "");

      let body = "Hello Managers,\n\n" +
                 "A new Negative Job Safety Observation has been recorded for " + associateName + ".\n\n" +
                 ccaNote +
                 "Original Observation Note: " + note + "\n\n" +
                 "Action Required:\n" +
                 "1. Please schedule a coaching conversation with the associate:\n   " + calendarLink + "\n\n" +
                 "2. Please fill out the Coaching Record Form after the conversation:\n   " + coachingLink + "\n\n" +
                 "Thank you,\nJSO Tracking System";

      MailApp.sendEmail({
        to: MANAGER_EMAIL,
        subject: subject,
        body: body
      });

    } else if (observationType === "Positive") {
      // Send an email for EVERY positive JSO
      const loveCardLink = "https://docs.google.com/forms/d/e/1FAIpQLSfCDTa-LcAo64xG6BBRrwWTl5BP3Ky17qUDR3Q8pzDHy8JqaA/viewform";
      const subject = "🎉 Positive JSO Recorded: " + associateName + " (Total: " + count + ")";
      const body = "Hello Managers,\n\n" +
             "This is an automated notification that " + associateName + " has just received a Positive Job Safety Observation.\n\n" +
             "This brings their total to " + count + " Positive JSOs!\n\n" +
             "Please take a moment to congratulate them on their excellent work!\n\n" +
             "Please fill out a Love card for their hard work here: " + loveCardLink + "\n\n" +
             "Thank you,\nJSO Tracking System";

      MailApp.sendEmail({
        to: MANAGER_EMAIL,
        subject: subject,
        body: body
      });
    }

  } catch (error) {
    Logger.log("Error handling emails: " + error.toString());
  }
}

function submitCoaching(data) {
  if (JSO_DATA_SHEET_ID === 'YOUR_NEW_JSO_SHEET_ID_HERE') {
    throw new Error("System not configured properly.");
  }

  try {
    const dataSpreadsheet = SpreadsheetApp.openById(JSO_DATA_SHEET_ID);
    const sheet = dataSpreadsheet.getSheetByName('Observations');
    if (!sheet) throw new Error("Could not find the 'Observations' tab.");

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) throw new Error("No data found.");

    // Get Observation IDs from Column 2
    const ids = sheet.getRange(2, 2, lastRow - 1, 1).getValues();
    let targetRow = -1;

    for (let i = 0; i < ids.length; i++) {
      if (ids[i][0] === data.id) {
        targetRow = i + 2; // +2 because range starts at row 2 and arrays are 0-indexed
        break;
      }
    }

    if (targetRow === -1) {
      throw new Error("Could not find the original observation record to update.");
    }

    // Update Columns 8, 9, 10, 11 (Policy, Perspective, Action Plan, Leader Notes)
    sheet.getRange(targetRow, 8, 1, 4).setValues([[
      data.policy,
      data.perspective,
      data.actionPlan,
      data.leaderNotes
    ]]);


    // Only processJSO logs detailed activities now.

    return { success: true };
  } catch (error) {
    Logger.log("Error in submitCoaching: " + error.toString());
    throw new Error("Failed to save coaching record. " + error.toString());
  }
}


// UPDATED: processJSO replaces submitJobSafetyObservation
function processJSO(data) {
  try {
    const timestamp = new Date();

    // Calculate the Actual UPH based on their time and pieces/pallets
    let uphText = "N/A";
    if (data.totalSeconds > 0 && data.totalCount > 0) {
        let uph = Math.round(data.totalCount / (data.totalSeconds / 3600));
        uphText = uph + " units/hr";
    }


    // Create HTML template for PDF
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; padding: 20px;">
        <h2 style="color: #0056b3; border-bottom: 2px solid #0056b3; padding-bottom: 10px;">Job Safety & Performance Observation</h2>

        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;"><strong>Date/Time:</strong></td>
            <td style="padding: 8px; border: 1px solid #ddd;">${timestamp.toLocaleString()}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;"><strong>Observing Leader:</strong></td>
            <td style="padding: 8px; border: 1px solid #ddd;">${data.leader}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;"><strong>Associate:</strong></td>
            <td style="padding: 8px; border: 1px solid #ddd;">${data.associate}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;"><strong>Function:</strong></td>
            <td style="padding: 8px; border: 1px solid #ddd;">${data.function}</td>
          </tr>
        </table>


        <h3 style="color: #333;">Checklist</h3>
        <ul style="line-height: 1.6;">
          ${(data.checklistResults || []).map(item => `<li><strong>${item.check}:</strong> ${item.notes || 'No notes'}</li>`).join('')}
        </ul>

        <h3 style="color: #333;">Performance Metrics</h3>
        <ul style="line-height: 1.6;">
          <li><strong>Total Time Observed:</strong> ${data.duration}</li>
          <li><strong>Total Count:</strong> ${data.totalCount || 0} ${data.type === 'pallet' ? 'Pallets' : 'Pieces'}</li>
          <li><strong>Observed UPH:</strong> ${uphText}</li>
        </ul>


        <h3 style="color: #333;">Activity Log</h3>
        <ul style="line-height: 1.6;">${data.activityLogs}</ul>

        <h3 style="color: #333; margin-top: 20px;">Associate Feedback</h3>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; width: 80%;">Do you feel you can maintain the pace performed for your entire shift?</td>
            <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${data.fbPace}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">Do you feel you have all the necessary skills required to do the job?</td>
            <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${data.fbSkills}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">Do you feel the need for additional training in the prescribed methods or procedures?</td>
            <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${data.fbTraining}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">Do you feel your work environment (Equipment, Facility, Layout, supplies) support the work you do?</td>
            <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${data.fbEnvironment}</td>
          </tr>
        </table>
        <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #0056b3; margin-bottom: 20px;">
          <strong>Feedback Notes:</strong><br>
          ${data.fbNotes}
        </div>

        ${data.signature ? `
        <div style="margin-top: 30px;">
            <p style="margin-bottom: 5px;"><strong>Associate Signature:</strong></p>
            <img src="${data.signature}" style="max-height: 100px; border: 1px solid #ddd;" alt="Signature">
        </div>` : '<p><em>No signature provided.</em></p>'}
      </div>
    `;


    // Create PDF
    const blob = Utilities.newBlob(htmlBody, MimeType.HTML).getAs(MimeType.PDF);
    blob.setName(`JSO_Report_${data.associate}_${timestamp.getTime()}.pdf`);


    // Email PDF to Managers
    MailApp.sendEmail({
      to: MANAGER_EMAIL,
      subject: `JSO Report: ${data.associate} (${data.function})`,
      body: `Please find attached the Job Safety & Performance Observation report for ${data.associate}, conducted by ${data.leader}.`,
      attachments: [blob]
    });


    logActivity(data);


    return { success: true };
  } catch (error) {
    Logger.log("Error in processJSO: " + error.toString());
    throw new Error("Failed to submit and send JSO PDF. " + error.toString());
  }
}